on:
  push:
    tags:
      - '[0-9].[0-9]+.[0-9]+' 

name: Pack ATHMovil.PurchaseSDK

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: msbuild Source/**/*.csproj /t:restore,rebuild,pack /p:Configuration=Release /p:version=${{ github.ref_name }}
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@3
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: Source/**/*.nupkg